Adapt To Changes In Memory Reading Implementation
Adapt to observation of exception thrown with call stack in memory measurement:
----
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'